### ISSUE TITLE
Is this datasets available?

### ISSUE THREAD

**Issue by suojifeng** [khizerzakir/Time-Series-Crop-Classification-Deep-Learning#1]
Is this datasets available?Thank you

**Comment by khizerzakir** [comment]
> Is this datasets available?Thank you

I will check with my supervisors and let you know.

**Comment by suojifeng** [comment]
> > Is this datasets available?Thank you
> 
> I will check with my supervisors and let you know.
Thank you so much

**Comment by khizerzakir** [comment]
> > > Is this datasets available?Thank you
> > 
> > 
> > I will check with my supervisors and let you know.
> > Thank you so much

Check the repo, I have updated it with the references, you can use the dataset from there.
